apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb
      image: mariadb10.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"